### PR TITLE
Fix #10

### LINKED ISSUE #10: Accept Consent request session model incorrect
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-client-go/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-client-go/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The model for the accept consent session request seems incorrect -

https://github.com/ory/hydra-client-go/blob/master/model_consent_request_session.go#L23

It's type `"idToken": map[string]map[string]interface{}` when the API docs suggest it is `"idToken": map[string]interface{}`

The JS (node) api also sends an object of key: string, value: any. The dart api also has a similar mapping, but of String: JSONObject.

I can't find any suitable examples of what the body should be..

is this correct?
```
idToken: {
  email: { email: "hello@email.com" },
  name: { name: "foo bar" },
}
```

The openapi consumer crashes

### Reproducing the bug

Create a login session/ consent

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

1.11.7

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

Kubernetes

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by matejkramny**
Update IdToken and AccessToken definitions

Change from `map[string]map[string]interface{}` to `map[string]interface{}` as per documentations and other clients

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you for the PR! Unfortunately this library is autogenerated and any changes made in this PR will be overwritten. You will need to make these changes in Ory Hydra directly (in the go code for example) :)

**Comment by kotyara85** [comment]
It's actually should be
```
// ConsentRequestSession struct for ConsentRequestSession
type ConsentRequestSession struct {
	// AccessToken sets session data for the access and refresh token, as well as any future tokens issued by the refresh grant. Keep in mind that this data will be available to anyone performing OAuth 2.0 Challenge Introspection. If only your services can perform OAuth 2.0 Challenge Introspection, this is usually fine. But if third parties can access that endpoint as well, sensitive data from the session might be exposed to them. Use with care!
	AccessToken interface{} `json:"access_token,omitempty"`
	// IDToken sets session data for the OpenID Connect ID token. Keep in mind that the session'id payloads are readable by anyone that has access to the ID Challenge. Use with care!
	IdToken interface{} `json:"id_token,omitempty"`
}
```

**Comment by aeneasr** [comment]
We fixed this in the OpenAPI spec, but it's not yet released :)

**Comment by kotyara85** [comment]
rgr

**Pull request closed without merging**
